miku-doujin.com##[href*="https://t.ly/ufafat"] > .img-thumbnail
miku-doujin.com##[href*="https://t.ly/ufanance"] > .img-thumbnail
miku-doujin.com##[href*="https://t.ly/juad8888"] > .img-thumbnail
miku-doujin.com##[href*="https://t.ly/lockdown1688"] > .img-thumbnail
miku-doujin.com##[href*="https://t.ly/lotto7777"] > .img-thumbnail
miku-doujin.com##[href*="https://t.ly/kingdom66"] > .img-thumbnail
miku-doujin.com##[href*="https://t.ly/hydra8888"] > .img-thumbnail
miku-doujin.com##[href*="https://t.ly/1688sagame"] > .img-thumbnail
miku-doujin.com##[href*="https://t.ly/panama8888"] > .img-thumbnail
miku-doujin.com##[href*="https://t.ly/lotto432"] > .img-thumbnail
miku-doujin.com##[href*="https://betflik168.me"] > .img-thumbnail
miku-doujin.com##[href*="https://sexybaccarat4.com/"] > .img-thumbnail
miku-doujin.com##[href*="https://cutt.ly/neon24h_miku"] > .img-thumbnail
miku-doujin.com##[href*="https://play.ufa11k.co/signup"] > .img-thumbnail
miku-doujin.com##[href*="https://askmeslot.asia/"] > .img-thumbnail
miku-doujin.com##[href*="https://cittapartecipata.com/"] > .img-thumbnail
miku-doujin.com##[href*="https://t.ly/ufazeed"] > .img-thumbnail
miku-doujin.com##[href*="https://t.ly/ufac4"] > .img-thumbnail
miku-doujin.com##[href*="https://t.ly/brazil999"] > .img-thumbnail
miku-doujin.com##[href*="https://t.ly/sexy1688"] > .img-thumbnail
hentaithai.com##[src*="//HentaiThai.com/banner/main_top.php?no=1"]
hentaithai.com##[src*="//HentaiThai.com/banner/main_top.php?no=2"]
hentaithai.com##[src*="//HentaiThai.com/banner/main_top.php?no=3"]
hentaithai.com##[src*="//hentaithai.com/banner/main_top.php?no=1"]
hentaithai.com##[src*="//hentaithai.com/banner/main_top.php?no=2"]
hentaithai.com##[src*="//hentaithai.com/banner/main_top.php?no=3"]
hentaithai.com##[src*="//hentaithai.com/banner/topic_side.html"]
hentaithai.com##.banner_sidebar
hentaithai.com###image-40 > .link-next > .img-fluid
hentaithai.com###image-38 > .link-next > .img-fluid
www.xn--l3c0azab5a2gta.com##[src*="https://image.cdend.com/wp-content/uploads/2024/05/728x200-lalikabet66.gif"]
www.xn--l3c0azab5a2gta.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-lalikabet88.gif"]
www.xn--l3c0azab5a2gta.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-lalikabet168.gif"]
www.xn--l3c0azab5a2gta.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-boston777.gif"]
www.xn--l3c0azab5a2gta.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-ufafat.gif"]
www.xn--l3c0azab5a2gta.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-ufanance.gif"]
www.xn--l3c0azab5a2gta.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-Juad888.gif"]
www.xn--l3c0azab5a2gta.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-vip168sa.gif"]
www.xn--l3c0azab5a2gta.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-UFAC4.gif"]
www.xn--l3c0azab5a2gta.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-Lockdown168.gif"]
www.xn--l3c0azab5a2gta.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-brazil999.gif"]
www.xn--l3c0azab5a2gta.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-Hydra888.gif"]
www.xn--l3c0azab5a2gta.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-panama888.gif"]
www.xn--l3c0azab5a2gta.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-lotto77.gif"]
www.xn--l3c0azab5a2gta.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-ufazeed.gif"]
www.xn--l3c0azab5a2gta.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-UFA191.gif"]
www.xn--l3c0azab5a2gta.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-LOTTO432.gif"]
www.xn--l3c0azab5a2gta.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-SA1688.gif"]
www.xn--l3c0azab5a2gta.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-sexygame1688.gif"]
doujin-th.com##[src*="//doujin-th.com/banner/main_top_1.html"]
doujin-th.com##[src*="//doujin-th.com/banner/main_top_2.html"]
doujin-th.com##[src*="//doujin-th.com/banner/main_top_3.html"]
doujin-th.com##div.container:nth-of-type(3)
www.slow-manga.com##[src*="https://image.cdend.com/wp-content/uploads/2024/05/728x200-lalikabet66.gif"]
www.slow-manga.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-lalikabet168.gif"]
www.slow-manga.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-lalikabet88.gif"]
www.slow-manga.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-Hydra888.gif"]
www.slow-manga.com##[src*="https://www.slow-manga.com/wp-content/uploads/2024/11/565595626.gif"]
www.slow-manga.com##[src*="https://www.slow-manga.com/wp-content/uploads/2024/11/Sexy24hr-BANNER-GIF-728x200-NEW-DESIGN-2025-03.gif"]
www.slow-manga.com##[src*="https://www.slow-manga.com/wp-content/uploads/2024/11/728x200-BANNER-GIF-NEON24H.gif"]
www.slow-manga.com##[src*="https://www.slow-manga.com/wp-content/uploads/2024/11/728x200-LUKWIN88-BANNER-GIF.gif"]
www.slow-manga.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-ufazeed.gif"]
www.slow-manga.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-panama888.gif"]
www.slow-manga.com##[src*="https://image.cdend.com/wp-content/uploads/2024/03/728x200-lotto77.gif"]
miku-doujin.com##[href*="https://www.betflik168.biz/"] > .img-thumbnail
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/lalikabet88.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/LALIKABET168.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/lalikabet66.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/JUAD888.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/VIP168SA.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/188Bet.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/1_1.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/1_2.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/1_3.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/1_4.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/365.gif"]
www.anime-suba.com##[href*="https://stopmotioncentral.com/"] > [src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/fafa188.gif"]
www.anime-suba.com##[href*="https://www.jewelhospitality.com/"] > [src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/fafa188.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/1x2.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/img03/BRAZIL999.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/img03/SEXYGAME1688.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/img02/Lockdown168.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/img02/1688SAGAME.gif"]
www.anime-suba.com##[href*="https://www.anenglishmanscastle.com/"] > [src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/fafa168.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/FAFA178.gif"]
www.anime-suba.com##[href*="https://vsphere-land.com/"] > [src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/fafa168.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/fafa168new2.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/C8196.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/UFA191.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/8196F.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/D8196.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/U8196.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/SLOT_True_wallet.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/fafa456.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/FAFA987.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/BETWIN.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/j789.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/slotking777.gif"]
www.anime-suba.com##[href*="https://starlingtalk.com/"] > [src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/spez666.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/sepz666_3.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/SPEZ888.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/slotwallet.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/newbet789.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/Fullbet789.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/Joker123th.gif"]
www.anime-suba.com##.white_content03 > p > [href*="javascript:void(0)"] > [src*="https://www.anime-suba.co/imges/close.png"]
www.anime-suba.com##.white_content02
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/img05/PGK44.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/img05/askmeslott.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/img05/ambslot44.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/img05/huc99.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/img05/ufa11k.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/img06/j789.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/BOSTON77.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/UFAFAT.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/KINGDOM66.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/UFANANCE.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/HYDRA88.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/SBF.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/FUN88.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/ufakick.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/colf.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/huaylike.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/Reelx_365.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/789BET.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/Jun88.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/AMB888.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/jackpot_777.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/askmeslot.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/slot99.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/sexygame992.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/pgjoker69.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/UFA365.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/UFABET_7M.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/Okslot_2.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/Okslot.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/Freeslot.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/pigpg.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/FAFA666.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/betwin.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/Slot_888.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/Football_online_888.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/Bacala_1.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/casino_oneline_betting.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/LIKELOTTO888.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/slotwin.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/slot888.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/jackpot999.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/raz99.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/A8196.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/sexybaccarat168.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/UFARUAY.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/Hengjing168.gif"]
www.anime-suba.com##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/pgslot99.gif"]
www.anime-suba.com##[href*="https://orpheumkids.com/"] > [src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/spez666.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/img03/BRAZIL999.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/img03/SEXYGAME1688.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/img02/Lockdown168.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/img02/1688SAGAME.gif"]
www.anime-suba.co##.white_content03
www.anime-suba.co##.white_content02 > p > [href*="javascript:void(0)"] > [src*="https://www.anime-suba.co/imges/close.png"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/LALIKABET168.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/lalikabet88.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/lalikabet66.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/JUAD888.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/VIP168SA.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/188Bet.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/365.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/img05/PGK44.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/img05/askmeslott.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/img05/ambslot44.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/img05/huc99.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/img05/ufa11k.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/img06/j789.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/1_1.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/1_2.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/1_3.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/1_4.gif"]
www.anime-suba.co##[href*="https://stopmotioncentral.com/"] > [src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/fafa188.gif"]
www.anime-suba.co##[href*="https://www.jewelhospitality.com/"] > [src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/fafa188.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/1x2.gif"]
www.anime-suba.co##[href*="https://www.anenglishmanscastle.com/"] > [src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/fafa168.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/FAFA178.gif"]
www.anime-suba.co##[href*="https://vsphere-land.com/"] > [src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/fafa168.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/fafa168new2.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/C8196.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/UFA191.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/8196F.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/D8196.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/U8196.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/SLOT_True_wallet.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/fafa456.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/FAFA987.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/BETWIN.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/j789.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/slotking777.gif"]
www.anime-suba.co##[href*="https://starlingtalk.com/"] > [src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/spez666.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/sepz666_3.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/SPEZ888.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/slotwallet.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/Freeslot.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/Okslot.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/Okslot_2.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/UFA365.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/sexygame992.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/789BET.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/Jun88.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/ufakick.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/huaylike.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/colf.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/UFAFAT.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/BOSTON77.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/KINGDOM66.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/UFANANCE.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/SBF.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/HYDRA88.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/FUN88.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/Reelx_365.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/AMB888.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/jackpot_777.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/slot99.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/newbet789.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/Fullbet789.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/Joker123th.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/pgslot99.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/Hengjing168.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/UFARUAY.gif"]
www.anime-suba.co##[href*="https://orpheumkids.com/"] > [src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/spez666.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/sexybaccarat168.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/A8196.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/raz99.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/jackpot999.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/slot888.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/slotwin.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/LIKELOTTO888.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/casino_oneline_betting.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/Bacala_1.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/Football_online_888.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/Slot_888.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/betwin.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/FAFA666.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/pigpg.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/UFABET_7M.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/pgjoker69.gif"]
www.anime-suba.co##[src*="https://www.anime-suba.co/Anime-Suba/Admin/imgAnadvertisement/askmeslot.gif"]
